name: "[CI]master push"
on:
  push:
    paths-ignore:
      - '.github/**'
      - '**/deploy/helm/**'
      - '**/skaffold.template.yaml'
    branches:
      - master

  workflow_dispatch:

env:
  ORGANIZATION: pyengine


jobs:
  versioning:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.job1.outputs.VERSION }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: calculate current date
        run: |
          sudo ln -sf /usr/share/zoneinfo/Asia/Seoul /etc/localtime
          echo "TIME=$(date +'%Y%m%d.%H%M%S')" >> $GITHUB_ENV
      - name: calculate_version
        id: job1
        run: |
          echo "::set-output name=VERSION::$(cat VERSION | cut -c 2-).${{ env.TIME }}"

  docker:
    if: github.repository_owner == 'cloudforet-io'
    needs: versioning
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ needs.versioning.outputs.version }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: get service name
        run: |
          echo "SERVICE=$(echo ${{ github.repository }} | cut -d '/' -f2)" >> $GITHUB_ENV
      -
        name: Build and push (docker hub)
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./apps/web/Dockerfile
          build-args: |
            TURBO_TOKEN=${{ secrets.TURBO_TOKEN }}
            TURBO_TEAM=${{ secrets.TURBO_TEAM }}
          push: true
          tags: pyengine/${{ env.SERVICE }}:latest, pyengine/${{ env.SERVICE }}:${{ env.VERSION }}
          cache-from: pyengine/${{ env.SERVICE }}:latest
          cache-to: type=inline


      - name: Slack
        if: always()
        uses: 8398a7/action-slack@v3.2.0
        with:
          status: ${{job.status}}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
          author_name: Github Action Slack
        env:
          SLACK_WEBHOOK_URL: ${{secrets.SLACK_WEBHOOK_URL}}
