name: "[CI]reflect branch update to master"
on:
  repository_dispatch:
    types: [update_master_version]

jobs:
  reflect_branch_update:
    env:
      VERSION: ${{ github.event.client_payload.version }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: check version format
        run: |
          if [[ !(${{ env.VERSION }} =~ ^v[0-9]\.[0-9]\.[0-9](.*)$) ]];
            then exit 1
          fi
      - name: get existing official version
        run: |
          echo "current=$(cat src/VERSION | cut -c 2-6)" >> $GITHUB_ENV
          echo "new_ver=$(echo ${{ env.VERSION }} | cut -c 2-6)" >> $GITHUB_ENV
      - name: Is new_ver is latest?
        run: |
          if [ $(echo ${{ env.current }} | cut -c 1) \> $(echo ${{ env.new_ver }} | cut -c 1) ]
          then
            echo "LATEST_TAG=false" >> $GITHUB_ENV
          else
            if [ $(echo ${{ env.current }} | cut -c 3) \> $(echo ${{ env.new_ver }} | cut -c 3) ]
            then
              echo "LATEST_TAG=false" >> $GITHUB_ENV
            else
              if [ $(echo ${{ env.current }} | cut -c 5) \> $(echo ${{ env.new_ver }} | cut -c 5) ]
              then
                echo "LATEST_TAG=false" >> $GITHUB_ENV
              else
                echo "LATEST_TAG=true" >> $GITHUB_ENV
              fi
            fi
          fi
      - name: Latest Update - update version file
        if: ${{ env.LATEST_TAG }} == 'true'
        uses: actions/checkout@v2
      - run: |
          echo ${{ env.VERSION }} > src/VERSION
          if [[ $(cat src/VERSION) =~ v[0-9]\.[0-9]\.[0-9]\.([0-9]+) ]];
            then npm --no-git-tag-version version $(echo $(cat src/VERSION | cut -c 2-6)-$(cat src/VERSION | cut -c 8-))
            else npm --no-git-tag-version version $(cat src/VERSION | cut -c 2-)
          fi
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "[CI/CD] release version ${{ env.VERSION }}"
          git push