name: "[Dispatch] Mirinae Release"

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Please enter branch (only master and release-x.y.z are allowed)'
        required: true
        default: 'master'
      version:
        description: 'Please enter version(x.y.z)'
        required: true
        default: '1.0.0'

env:
  BRANCH: ${{ github.event.inputs.branch }}
  VERSION: ${{ github.event.inputs.version }}
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
  TURBO_CACHE_SERVER_URL: ${{ github.event.inputs.turbo-cache-server-url }}

jobs:
  release:
    runs-on: ubuntu-latest

    services:
      turbo_cache:
        image: wanzargen/turbo-cache-server:latest
        env:
          PORT: 3000
          TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
          STORAGE_PROVIDER: git-repository
          STORAGE_PATH: console-artifacts
          GIT_REPOSITORY: ${{ vars.TURBO_CACHE_SERVER_GIT_REPOSITORY }}
          GIT_BRANCH: ${{ vars.TURBO_CACHE_SERVER_GIT_BRANCH }}
          GIT_USER_NAME: ${{ vars.GIT_USERNAME }}
          GIT_USER_EMAIL: ${{ vars.GIT_EMAIL }}
          GIT_USER_PASSWORD: ${{ secrets.PAT_TOKEN }}
        ports:
          - 3000:3000
        options: >-
          --health-cmd "curl -f GET 'http://localhost:3000/v8/artifacts/status' -H 'Authorization: Bearer $TURBO_TOKEN'"
          --health-interval 10s
          --health-timeout 10s
          --health-retries 10
          --health-start-period 30s

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ env.BRANCH }}
          token: ${{ secrets.PAT_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Restore cached node_modules
        id: restore-node-cache
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.OS }}-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-modules-

      - name: Install dependencies
        if: steps.restore-node-cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Build
        env:
          NODE_ENV: "production"
        run: |
          npm run build -- --filter=@spaceone/design-system --token="${{ secrets.TURBO_TOKEN }}" --team="${{ secrets.TURBO_TEAM }}" --api="http://localhost:3000"

#      - name: Release
#        env:
#          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
#          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
#        run: |


  notification:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - name: Slack
        if: always()
        uses: 8398a7/action-slack@v3.15.0
        with:
          status: ${{job.status}}
          fields: repo,message,commit,author,action,ref,workflow,job
          author_name: Github Action Slack