name: FetchTranslation
on:
  workflow_dispatch:
jobs:
  authorize:
    if: github.repository_owner == 'spaceone-dev'
    runs-on: ubuntu-latest
    steps:
    - uses: octokit/request-action@v2.0.0
      with:
        route: GET /repos/:repository/collaborators/${{ github.actor }}
        repository: ${{ github.repository }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    needs: [authorize]
    runs-on: ubuntu-latest
    steps:
      - name: git clone
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          cd ./src/translations
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Sync data
        env:
          SHEET_URL: https://docs.google.com/spreadsheets/d/1K81JbXNLtui93caZu_MyQdy8lv5qxyo69AvlKRA98bM
          CREDENTIAL_BASE64: ${{ secrets.CREDENTIAL_BASE64 }}
          DATA_SHEET_NAME: origin
          SYNC_SHEET_NAME: data
          META_SHEET_NAME: meta
          UNSYNC_FIELD: unsync
          ID_FIELD: Translation ID
        run: |
          cd ./src/translations
          python3 fetch_language-pack.py
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v2
        with:
          branch: translation-auto-patch
          title: '[Bot] Update Language Pack'
          commit-message: Modified language pack
          body: |
            Update by [spread-sheet](https://docs.google.com/spreadsheets/d/1K81JbXNLtui93caZu_MyQdy8lv5qxyo69AvlKRA98bM)
