name: "[Dispatch] Preview Deploy with Vercel"

on:
  workflow_dispatch:
    inputs:
      project:
        description: 'enter vercel project name'
        required: true
        default: 'feedback'

env:
  TEAM_NAME: ${{ vars.VERCEL_TEAM_NAME }}
  PROJECT_NAME: ${{ github.event.inputs.project }}
  VERCEL_TOKEN: ${{ secrets.VERCEL_CLOUDFORET_TOKEN }}

jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Checkout Vercel Target Project
        run: vercel link --yes --scope=${{ env.TEAM_NAME }} --project=${{ env.PROJECT_NAME }} --token=${{ env.VERCEL_TOKEN }}
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --token=${{ env.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ env.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ env.VERCEL_TOKEN }}
